### ISSUE TITLE
有一个可以改进的地方

### ISSUE THREAD

**Issue by kiinlam** [alienzhou/web-highlighter#17]
考虑如下HTML：

```html
<p>春天到了</p>
<p>花儿开了</p>
```

如果是在第一个p标签结尾开始创建选区，界面上实际选中的是在第二个p标签里的文字，此时，`删除`按钮会出现在第一个p标签的结尾，检查元素时，可以看到此处生成了一个空子节点的span标签。

这种情况可以在第一段结尾空白处按下鼠标并往下拖拽后出现。造成`删除`按钮跟高亮区域分离较远。

**Comment by alienzhou** [comment]
我后续优化一下这种情况。感谢反馈 😊

**Comment by alienzhou** [comment]
由于某些元素后存在空文本节点或换行符，所以该空节点也被加上了span。

目前来看，一种处理方式就是在 `Painter::highlightRange` 里再加入一些判断过滤掉此类文本节点([src/painter/index.ts](https://github.com/alienzhou/web-highlighter/blob/master/src/painter/index.ts#L47))，一种简单的实现例如：
```JavaScript
let $selectedNodes = getSelectedNodes($root, range.start, range.end, exceptSelectors);
$selectedNodes = $selectedNodes.filter(n => n.$node.textContent);
```

另一种方式是在上层应用时（例如仓库里提供的 example），添加对应的 hook，在其中进行过滤：

```JavaScript
highlighter.hooks.Render.SelectedNodes.tap(
    (id, nodes)  => nodes.filter(n => n.$node.textContent)
);
```

权衡之后，考虑还是让用户通过 hook 来自定义这种处理，库本身还是暴露最原始的选区；
同时，如果后续发现很多场景下的相同功能都要在 hook 中实现，可以再把这些功能下沉到库中。

不知道你觉得这种方式怎么样？

**Comment by kiinlam** [comment]
我想到的也是交给用户处理，过滤掉空内容的span节点。
当然，如果能在框架层面解决掉那就最好了。只是不知道这种需求有多少。

**Comment by alienzhou** [comment]
目前可以先通过暴露的接口能力在用户侧解决，后续类似需求或场景出现频繁时，可以将该功能抽取并内置进来。

**Comment by alienzhou** [comment]
#21
