### ISSUE TITLE
关于高亮问题交流

### ISSUE THREAD

**Issue by w1922616586** [alienzhou/web-highlighter#20]
您好  我自己曾写过这个功能 但我实现的很不理想  想跟您探讨下您的实现思路   不知是否方便

**Comment by alienzhou** [comment]
欢迎，我在一篇 blog 里介绍了大致的实现过程，如果感兴趣可以看一下（[文章链接](https://github.com/alienzhou/blog/issues/28) ）。有什么想法可以一起交流讨论

**Comment by zfx19890623** [comment]
您好，请问划词的时候可以进行批注操作吗？

**Comment by alienzhou** [comment]
> 您好，请问划词的时候可以进行批注操作吗？

目前这个库里没有包含批注功能，不过可以通过暴露的事件监听或者钩子来扩展与集成。

我们的产品在右侧是有笔记栏的（类似批注），两者可以通过事件或者全局状态来通信。由于笔记（批注）更注重业务交互逻辑，不同产品的交互差别大，不好满足定制化需求，所以没有把这部分放进来。

![Y18mdF8UiT](https://user-images.githubusercontent.com/9822789/64678049-632e8500-d4ab-11e9-99d6-f960bc90d17b.gif)

**Comment by alienzhou** [comment]
#23

**Comment by alienzhou** [comment]
Duplicate of #23
