### ISSUE TITLE
您好，请问在移动端使用的时候为什么会经常出现找不到元素的情况？

### ISSUE THREAD

**Issue by LawrenceQxy** [alienzhou/web-highlighter#24]
在移动端使用的时候经常根据高亮保存的位置信息重新进行高亮操作(fromStore)的时候会有Cannot read property 'nodeType' of undefined的报错，请问这是什么原因？

**Comment by alienzhou** [comment]
看这个报错大致是因为，基于持久化数据没有找到对应的dom节点。具体原因有可能是兼容性，也可能是调用时机等问题。
如果可以希望能提供进一步信息，例如可运行的错误复现示例，机型浏览器型号等。

**Comment by LawrenceQxy** [comment]
我把源码里高亮的标签从span改成ins，在$root下增加了一个空白的div以后就基本没复现过了
