### ISSUE TITLE
SelectedNodes Hook 的处理

### ISSUE THREAD

**Issue by dannyChyang** [alienzhou/web-highlighter#25]
### 场景
需要实现反向`exceptSelectors`的功能，即，将高亮功能限定在某个容器内
### 思路
使用`SelectedNodes`Hook 先对高亮区创建前的nodeList进行过淲

``` js
// 相关代码
highlighter.hooks.Render.SelectedNodes.tap((id, doms) => {
        // 仅高亮容器内部
        const container = self.$refs.pre;
        const validNodes = doms.filter(({$node}) => container.compareDocumentPosition($node) === 20)
        console.log('SelectedNodes', doms, validNodes);
        return validNodes;
      })
```
### 问题
过滤后，在`event.CREATE`事件回调中，取得的`source.startMeta`、`source.endMeta`、`source.text`，没有根据过滤结果重新设置。

**Comment by alienzhou** [comment]
感谢反馈。

确实会有这个现象。不过不知道你这边是否会依赖`startMeta `、`endMeta `、`text ` 的数据做一些其他事情，如果只是选取还原，因为有这个 Hook 的存在，应该还是会保持一致。

---

此外，关于提到的“将高亮功能限定在某个容器内”这个需求，不知道你的场景下，是否可以用

```JavaScript
var highlighter = new Highlighter({
    $root: self.$refs.pre
});
```

[这个配置](https://github.com/alienzhou/web-highlighter/blob/master/README.zh_CN.md#highlighter--new-highlighteropts)来实现。
