### ISSUE TITLE
你好，请问在移动端浏览器(safari,chrome)怎样设置才能选中内容并高亮？

### ISSUE THREAD

**Issue by buxingzhe5** [alienzhou/web-highlighter#26]
非常感谢作者web-highlighter，它让一个业余爱好者做出了一个可以自己使用的小应用。

我现在正在做移动端的内容，请问，怎样才能做到选中后高亮显示选中内容？

**非常感谢！**

**Comment by alienzhou** [comment]
感谢反馈。

由于项目之前是用于桌面浏览器的，所以只监听了mouse相关事件（`mouseup`,`mouseover`）；不过移动端这些事件都不会触发，对应的需要在移动端把 `mouseup` 改为 `touchend` 这类事件。

可能需要在源码里加个浏览器判断，来在不同环境下绑定不同的事件。例如 [src/index.ts](https://github.com/alienzhou/web-highlighter/blob/master/src/index.ts#L106-L107)。

近期我会看一看这个问题。

**Comment by buxingzhe5** [comment]
再次谢谢作者。

**Comment by alienzhou** [comment]
目前在 0.4.0-beta.0  版本添加了移动设备支持。
#30

**Comment by buxingzhe5** [comment]
谢谢。

在 2019年12月20日星期五，Alien ZHOU <notifications@github.com> 写道：
