### ISSUE TITLE
如何阻止跨行标注呢？

### ISSUE THREAD

**Issue by xulijing626** [alienzhou/web-highlighter#35]
现状 ：一次能标记好几行的数据
期望： 只能一行一行的标记，不允许跨行标记

**Comment by xulijing626** [comment]
就是希望一次标记不能标不同parentIndex的数据

**Comment by alienzhou** [comment]
可以试下 SelectedNodes 钩子，它支持在高亮前把一些节点过滤掉。
https://github.com/alienzhou/web-highlighter/blob/master/docs/ADVANCE.zh_CN.md#renderselectednodes
钩子接收目前选中的所有节点，需要返回要被高亮的部分。默认情况下相当于全部返回。

例如可以判断，如果parentid不同就返回空数组（相当于禁止高亮），或者只取其中一部分。

**Comment by xulijing626** [comment]
解决了、谢谢
