### ISSUE TITLE
npm包的dist文件和本地使用代码build的文件不一致

### ISSUE THREAD

**Issue by CoderKwong** [alienzhou/web-highlighter#38]
使用npm的包调用fromStore 会出现nodeType undefind问题，经过比对后发现是编译后代码不一致。

npm包的dist
![image](https://user-images.githubusercontent.com/12517739/81329176-bc00fc80-90d0-11ea-8895-f8e30a026de2.png)
使用代码编译的dist
![image](https://user-images.githubusercontent.com/12517739/81329315-ef438b80-90d0-11ea-9864-b1d6d2307508.png)

**Comment by alienzhou** [comment]
建议提供一下npm安装的版本。

如果没猜错，上面安装的版本应该是 0.6.0-beta.0 的，目前 repo 的 master 保留的是稳定版的 0.5.0。0.6.0-beta.0 的代码在 feat/deserialize-hook 分支上，引入了一个新 hook。对应的在 `fromStore` 最后添加了一个新的可选参数。理论上这个参数和特性不会影响到原有的方法。

你可以用其他版本再测试一下。如果新的 hook 对原有功能产生影响，估计就是引入了一个 bug。

**Comment by CoderKwong** [comment]
> 建议提供一下npm安装的版本。
> 
> 如果没猜错，上面安装的版本应该是 0.6.0-beta.0 的，目前 repo 的 master 保留的是稳定版的 0.5.0。0.6.0-beta.0 的代码在 feat/deserialize-hook 分支上，引入了一个新 hook。对应的在 `fromStore` 最后添加了一个新的可选参数。理论上这个参数和特性不会影响到原有的方法。
> 
> 你可以用其他版本再测试一下。如果新的 hook 对原有功能产生影响，估计就是引入了一个 bug。

npm: 6.13.7
yarn: 1.22.0
node: v13.9.0
os: mac Os 10.15.4

**Comment by CoderKwong** [comment]
排查过后发现，问题并不是多的参数引起的，而是在使用时查找node节点的层级问题引发，这是我使用的代码：
![image](https://user-images.githubusercontent.com/12517739/81583461-01307180-93e4-11ea-8377-8807ad6491ff.png)
这个是源码中查找节点的逻辑：
![image](https://user-images.githubusercontent.com/12517739/81583563-21f8c700-93e4-11ea-99a8-6eb444bf1156.png)
由于，我的$root就是当前装着文案的节点，就会抛出这个错误。
但是却可以在$root中生成高亮文案，感觉这个应该修改，或者是在文档中说明使用formstore的注意事项

**Comment by alienzhou** [comment]
这个问题我晚上复现一下看看。感谢反馈

**Comment by alienzhou** [comment]
目前在 fix_only-root-node 分支修复了一下 root 下没有子 dom 节点时的处理问题。可以先 checkout 这个分支，在本地 build 测试一下。
#39

**Comment by alienzhou** [comment]
[release v0.5.1](https://github.com/alienzhou/web-highlighter/releases/tag/v0.5.1) and fix this bug
