### ISSUE TITLE
请问如何实现两种高亮style,并且相互可以重叠

### ISSUE THREAD

**Issue by muchcool** [alienzhou/web-highlighter#45]
两种高亮style我添加好了,比如一种是下划线,一种是黄色背景
但现在两次选区有重叠部分的话,只会第二次选区的style覆盖第一次的,
如何能做到重叠部分能下划线和黄色同时存在呢?

**Comment by alienzhou** [comment]
部分重合（intersection）区域会被分割为一个新的节点并重新包裹。目前包裹时是使用 option 中当前的 className 值作为 CSS 类。

因此，通过 `.setOption` 动态改变 className 后，新创建的选区中，与老选区重合的区域只会表现出新的样式。但是 hover 或 click 时，你可以为这些元素重新设置样式，从而使激活时该选区的样式是正确的。

**Comment by muchcool** [comment]
> 部分重合（intersection）区域会被分割为一个新的节点并重新包裹。目前包裹时是使用 option 中当前的 className 值作为 CSS 类。
> 
> 因此，通过 `.setOption` 动态改变 className 后，新创建的选区中，与老选区重合的区域只会表现出新的样式。但是 hover 或 click 时，你可以为这些元素重新设置样式，从而使激活时该选区的样式是正确的。不知道这样的效果是否满足你的需求？

谢谢回答!
那么hover或click时为这些元素重新设置样式的话,是如何办到的呢?如何知道哪个id是哪个样式的?

或者, 能有什么办法,只允许某一种高亮style覆盖另一种,而不允许反过来吗?

**Comment by alienzhou** [comment]
> 那么hover或click时为这些元素重新设置样式的话,是如何办到的呢?

可以在 hover 或 click 事件里拿到 id，然后通过 `.getDoms(id)` 方法取到该高亮区域所有的包裹元素，为它们设置样式。

**Comment by alienzhou** [comment]
> 只允许某一种高亮style覆盖另一种

样式覆盖主要是通过 CSS 选择器优先级，你可以让优先的样式的 CSS 选择器高一点

**Comment by muchcool** [comment]
明白了,谢谢!
