### ISSUE TITLE
This highlight source isn't rendered. May be the exception skips it or the dom structure has changed.

### ISSUE THREAD

**Issue by khazidhea** [alienzhou/web-highlighter#47]
Hello. First of all, that's a pretty nice library, but I'm getting this error. Actually two errors:

![image](https://user-images.githubusercontent.com/1207334/84200920-46ba8a00-aac9-11ea-8291-78821788962e.png)

My setup is that I save the highlights in my database and then I send them to the template and use `fromStore()`. But if I delete one of my highlights somewhere at the start of the page in can sometimes break rendering for all of the highlights below it. 

I've just read (using google translate) in the Chinese article you've linked in the README that user hast to delete from back to front in the order of addition. Is it still the case? Are there any workarounds?

**Comment by kirubakaran** [comment]
Thank you for the great library @alienzhou I have the same issue too. Thanks in advance!

**Comment by alienzhou** [comment]
The reason is probably that the dom's structure changed. But these are high-level warnings, more details may be needed.

Can you provide a minimum demo which may reproduce such errors?

**Comment by khazidhea** [comment]
@alienzhou I think the DOM structure is being changed by inserting the <span> tags of the highlights.

I'll set up a minimum demo and link it in this thread a bit later.
