### ISSUE TITLE
选词之后好像无法ctrlC来复制?

### ISSUE THREAD

**Issue by muchcool** [alienzhou/web-highlighter#48]
请教一个问题, 
比如sample里自动高亮的话,好像就无法进行ctrl+C来复制所选文字?

有什么解决办法吗?

**Comment by alienzhou** [comment]
ctrl+C 复制的文字应该是需要文字处于被浏览器原生 selection 选中的状态。但是，目前高亮后会调用 `window.getSelection().removeAllRanges()` 来清除浏览器的原生选区。

之所以这么设计，是参考了medium等常见产品的交互。大致的交互逻辑是：

1. 用户拖动鼠标选择一段文本，此时是浏览器原生的“高亮”（selection）；
2. 页面上（文本附近）会弹出一个小工具框，工具框内会包含一个「高亮」按钮（或者还有一个复制按钮）；
3. 此时用户可以直接 ctrl c，因为浏览器的原生 selection 还在；
4. 如果用户想要高亮，则点击高亮按钮，此时会通过类库实现高亮，同时取消原生selection

同时保留原生 selection 效果和类库的 selection 效果可能在展示上会比较奇怪。

如果是希望实现复制文字功能，不知道是否可以在业务侧实现一个包含复制按钮的工具框，调用复制相关的浏览器 API 来实现呢？

**Comment by muchcool** [comment]
的确如你所说,
就算把window.getSelection().removeAllRanges()放到后面去执行,同时保留原生 selection 效果和类库的 selection 效果的话,显示就很奇怪.
而如果先不保留类库的 selection 效果(不执行highlighter.fromRange)的话,又无法获取position来弹出menu工具框按钮了.

**Comment by kaijiaLin** [comment]
@muchcool 这里最后咋解决的呢？

**Comment by muchcool** [comment]
并没有解决...只好直接把选择的文字放入粘贴板
