### ISSUE TITLE
className如何能动态改变

### ISSUE THREAD

**Issue by weiwangwang** [alienzhou/web-highlighter#49]
请教作者，我的问题是如何动态的改变className，我的需求是切换不同的颜色来完成标记，万分感谢

**Comment by alienzhou** [comment]
目前在实例上提供了一个 `.setOption` 的 API 方法，接收的参数和初始化时的 [options](https://github.com/alienzhou/web-highlighter#1-options) 一样，可以试下这个方法。

你可以在需要改变 className 时调用这个方法传入你的 className：

```JavaScript
highlighter.setOption({
    style: {
        className: 'another-class-name'
    }
})
```
