### ISSUE TITLE
Update Documentation when using fromRange

### ISSUE THREAD

**Issue by Aviking88** [alienzhou/web-highlighter#55]
When using `highlighter.fromRange(range)` we should first execute `highlighter.run()` then only it works, it would be good if we update the doc for the same.

**Comment by alienzhou** [comment]
The methods `.fromRange()` and `.run()` are designed to have no dependency. If you find that, it maybe a bug.

I wrote [some simple unit tests](https://github.com/alienzhou/web-highlighter/blob/v0.7.0/test/api.spec.ts#L27) in `api.spec.ts` which call `.fromRange()` or `.fromStore()` without calling `.run()`. You could provide a minimum sample if you find such special case. I will try to fix it.

Thanks!

**Comment by Aviking88** [comment]
ok @alienzhou , Thanks for looking into, I will share a sample for the same.

**Comment by Aviking88** [comment]
I just tried again and it seems to be working, I guess I had some cache issue in developement.

Thanks Again
