### ISSUE TITLE
能否自己调用画线生成的事件呢？

### ISSUE THREAD

**Issue by unclemin** [alienzhou/web-highlighter#63]
自定义调用生成画线的时机   选中文字后点击某个按钮生成

**Comment by alienzhou** [comment]
可以。
创建 highlight 对象后，不要调用 `.run` 方法就不会在选中后自动创建高亮区域；然后你可以在点击某个按钮的时候，获取页面的 [Range 对象](https://developer.mozilla.org/en-US/docs/Web/API/Range)，调用[`.fromRange(range)`方法](https://github.com/alienzhou/web-highlighter/blob/master/README.zh_CN.md#634-highlighterfromrangerange)。

一段简易的代码类似于：
```JavaScript
const highlighter = new Highlighter();
// 不调用 .run() 方法

document.getElementById('btn').addEventListener('click', function() {
  const selection = window.getSelection();
  if (!selection.isCollapsed) {
    highlighter.fromRange(selection.getRangeAt(0));
  }
});
```
