### ISSUE TITLE
IE下报错“正则表达式语法错误”

### ISSUE THREAD

**Issue by fw6** [alienzhou/web-highlighter#72]
# IE下提示正则表达式错误

## 错误描述
系统信息：
- browser: IE 11 (version: 1909 操作系统内部版本 18363.1440)
- os: windows 10
- web-highlighter@^0.7.1

![image](https://user-images.githubusercontent.com/45113594/111729760-c96b4380-88aa-11eb-8202-10c1e2062cf8.png)

## 问题原因

经检查，发现 `IE`未实现正则表达式语法flag的`u`（[RegExp.prototype.unicode](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode)）

![image](https://user-images.githubusercontent.com/45113594/111736539-fcb4cf00-88b8-11eb-9527-b28efef5c621.png)

在 `./src/util/is.mobile.ts`文件里面，修改正则 为 `const regMobile = /Android|iPhone|BlackBerry|BB10|Opera Mini|Phone|Mobile|Silk|Windows Phone|Mobile(?:.+)Firefox\b/i;`

**Comment by alienzhou** [comment]
#85
