### ISSUE TITLE
Highlighting in iframe

### ISSUE THREAD

**Issue by dattran2346** [alienzhou/web-highlighter#77]
Currently I have a remote html document and I want to implement the auto highlighting feature on the remote html using web-highlighter. Below is my code

``` javascript
<iframe id="iframe-id" src="https://content.my-server.com/file.html">

// after the iframe have been loaded
let iframeDocument = document.getElementById("iframe-id").contentWindow.document
let highlighter = new Highlighter({
      $root: iframeDocument.documentElement,
      wrap: "span",
      style: {
        className: "highlight-class"
      }
    })

highlighter.run()
```

I have tested this code on the local document and it works great, however, the I can't do auto highlighting on remote resource.

**Comment by alienzhou** [comment]
Maybe due to some security policies about the iframe. Is there any error or warning on the console?

**Comment by dattran2346** [comment]
It's is due to the CORS restriction. I can workaround it using `Disable Cross-Origin Restrictions` setting in Safari.
