### ISSUE TITLE
Create highlight wrapper inside another wrapper will take all the classes from parent

### ISSUE THREAD

**Issue by ruanyl** [alienzhou/web-highlighter#79]
Related commit 35560fa8f66bca78c7757f9975610b4cbca3cbc3

The issue I'm facing is when I create multi-color highlights, the highlight wrapper created inside another wrapper will take all the class of the parent wrapper. And this will override the color of the child wrapper if the child has a different color.

![image](https://user-images.githubusercontent.com/486382/120543379-ebc62500-c3f4-11eb-8735-d0ea5bdca7f7.png)

As you can see in the above screenshot, the highlight wrapper has both class names `highlighter-color-yellow` from its parent and `highlighter-color-green` which is the expected color of itself.

This `retain the wrapper's classname`  is a bit odd, what's the intention of this change?

**Comment by alienzhou** [comment]
#80

**Comment by alienzhou** [comment]
#80
